//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAProjectManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LivingArtPMContext : DbContext
    {
        public LivingArtPMContext()
            : base("name=LivingArtPMContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Recut> Recuts { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Scanned> Scanneds { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
    }
}
