//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public int PartsID { get; set; }
        public string PartFile { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Grain { get; set; }
        public string TagVariables { get; set; }
        public string JobName { get; set; }
        public string ItemName { get; set; }
        public string ItemPart { get; set; }
        public Nullable<int> CabinetNum { get; set; }
        public Nullable<int> PartNum { get; set; }
        public string MaterialName { get; set; }
        public string EdgeInfo { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> PartOffset { get; set; }
        public Nullable<int> PartPriority { get; set; }
        public Nullable<int> PartRotation { get; set; }
        public Nullable<int> UnitUnitID { get; set; }
        public Nullable<int> ScannedQuantity { get; set; }
        public int StatusID { get; set; }
    }
}
