//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recut
    {
        public int RecutID { get; set; }
        public Nullable<int> PieceID { get; set; }
        public string OrderDate { get; set; }
        public string Issue { get; set; }
        public int StatusStatusID { get; set; }
    }
}
