//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAProjectManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scanned
    {
        public int ScannedID { get; set; }
        public string DateTime { get; set; }
        public string BarCode { get; set; }
        public int StatusStatusID { get; set; }
        public int StatioStationID { get; set; }
    }
}
